#Server Port
server:
  port: 8787
  
#Spring Application Name
spring:
  application:
    name: Zuul-Server

config:
  saludo: Configuración Zuul Server en Config Server

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true

#Ribbon Activation
ribbon:
  eureka:
    enabled: true
